# Phase 2: $D_4$/Bolza and Klein-quartic benchmarks

This notebook validates the exact passive-Clifford engine on a CM abelian surface and a CM abelian threefold. The Klein-quartic calculation reproduces the gate counts reported in Proposition 6.8 of the paper.

In [1]:
import sys
from pathlib import Path

here = Path.cwd().resolve()
candidates = (here, here.parent, here / 'passive-cliffords')
project = next(path for path in candidates if (path / 'src' / 'gkp_passive_cliffords').exists())
workspace = project.parent
sys.path.insert(0, str(project / 'src'))
sys.path.insert(0, str(workspace / 'src'))

from gkp_systole import D4_PERIOD_MODEL, KLEIN_QUARTIC_PERIOD_MODEL
from gkp_passive_cliffords import period_model_logical_action, phase2_benchmark_table

## Exact polarized models

The parent project supplies period-derived exact Gram matrices, complex-structure numerators, and principal Riemann forms. Multiplying the principal form by $d$ produces type $(d,\ldots,d)$ while leaving the underlying polarized automorphism candidates unchanged.

In [2]:
for model in (D4_PERIOD_MODEL, KLEIN_QUARTIC_PERIOD_MODEL):
    model.validate()
    print(model.name)
    print('  dimension:', model.dimension)
    print('  CM field:', model.cm_field)
    print('  exact Riemann checks: PASS')

D4 principally polarized abelian surface
  dimension: 2
  CM field: Q(sqrt(-2))
  exact Riemann checks: PASS
Jacobian of the Klein quartic
  dimension: 3
  CM field: Q(sqrt(-7))
  exact Riemann checks: PASS


## Exact automorphism and logical-image orders

At level $2$, $-I$ fixes every two-torsion point, producing a kernel of order two. At level $3$, the actions are faithful.

In [3]:
rows = phase2_benchmark_table()
columns = [
    'model', 'level', 'polarization_type', 'kernel_order',
    'polarized_automorphism_order', 'logical_image_order',
    'action_kernel_order',
]
print(' | '.join(columns))
print(' | '.join(['---'] * len(columns)))
for row in rows:
    print(' | '.join(str(row[column]) for column in columns))

model | level | polarization_type | kernel_order | polarized_automorphism_order | logical_image_order | action_kernel_order
--- | --- | --- | --- | --- | --- | ---
D4 principally polarized abelian surface | 2 | (2, 2) | 16 | 48 | 24 | 2
D4 principally polarized abelian surface | 3 | (3, 3) | 81 | 48 | 48 | 1
Jacobian of the Klein quartic | 2 | (2, 2, 2) | 64 | 336 | 168 | 2
Jacobian of the Klein quartic | 3 | (3, 3, 3) | 729 | 336 | 336 | 1


## Interpretation

For the $D_4$/Bolza surface, the qubit-level image has order $24$ and the qutrit-level image has order $48$. For the Klein-quartic Jacobian, these orders are $168$ and $336$, reproducing the paper's benchmark. These are non-Pauli passive Clifford classes: Pauli gates and phases have already been quotiented out.

In [4]:
expected = {
    ('D4 principally polarized abelian surface', 2): (48, 24, 2),
    ('D4 principally polarized abelian surface', 3): (48, 48, 1),
    ('Jacobian of the Klein quartic', 2): (336, 168, 2),
    ('Jacobian of the Klein quartic', 3): (336, 336, 1),
}
lookup = {(row['model'], row['level']): row for row in rows}
for key, answer in expected.items():
    row = lookup[key]
    observed = (row['polarized_automorphism_order'], row['logical_image_order'], row['action_kernel_order'])
    assert observed == answer, (key, observed, answer)
    assert row['pairing_verified']
print('All Phase 2 benchmark checks passed.')

All Phase 2 benchmark checks passed.
